services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./backend/ollama-models
        target: /app/backend/ollama-models
        bind:
          create_host_path: true
    environment:
      - IN_DOCKER=true
    networks:
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - backend

networks:
  backend:
    driver: bridge
    external: false
    name: backend
