name: backend
channels:
  - defaults
dependencies:
  - python=3.13.2
  - requests=2.32.3
  - tqdm=4.67.1
  - pip:
      - docker==7.1.0
      - fastapi==0.115.12
      - uvicorn[standard]==0.34.2
      - pytest==8.3.5
      - black==25.1.0
      - flake8==7.2.0
      - psutil==7.0.0
      - mathplotlib==3.8.0