name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - requests=2.32.3
  - tqdm=4.67.1
  - git
  - pip
  - pip:
      - docker==7.1.0
      - fastapi==0.115.12
      - uvicorn[standard]==0.34.2
      - pytest==8.3.5
      - black==25.1.0
      - flake8==7.2.0
      - langchain
      - langchain-community
      - langchain-chroma
      - langchain-ollama
      - langchain-text-splitters