name: backend
channels:
  - defaults
dependencies:
  - python=3.13.2
  - requests=2.32.3
  - tqdm=4.67.1
  - pip:
      - docker==7.1.0
      - fastapi==0.115.12
      - uvicorn[standard]==0.34.2
      - pytest==8.3.5
      - black==25.1.0
      - flake8==7.2.0
      - langchain-text-splitters==0.3.8
      - langchain-core==0.3.62
      - langchain==0.3.25
      - langchain-chroma==0.2.4
      - langchain-ollama==0.3.3
      - langchain-community==0.3.24
      - chromadb==1.0.10
      - ollama==0.7.1