[tool.black]
line-length = 88
target-version = ['py38']
# Exclude all generated test files
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | ExampleTests/generatedTests
)/
'''