name: backend
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - requests=2.32.3
  - tqdm=4.67.1
  - docker-py=7.1.0
  - uvicorn=0.34.0
  - pytest=8.3.1
  - black=25.1.0
  - flake8=7.0.0
  - transformers=4.52.2
  - mccabe=0.7.0
  - pip
  - pip:
    - fastapi==0.115.1
    - langchain
    - langchain-community
    - langchain-ollama
    - langchain-chroma
    - langchain-text-splitters
    - keybert
    - beautifulsoup4