name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install tools
        run: pip install black flake8 pytest

      - name: Install project requirements
        run: pip install -r requirements.txt

      - name: Check formatting
        run: black --check .

      - name: Lint
        run: flake8 .

      - name: Run tests
        run: pytest -q
