name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Miniforge3, create + activate the `backend` env from environment.yml
      - name: Set up Conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          environment-file: environment.yml
          activate-environment: backend
          channels: conda-forge,defaults  # solver sees conda-forge first
          auto-activate-base: false # we rely on the named env only

      # Run quality gates & tests inside that env
      - name: Check formatting
        shell: bash -l {0}
        run: black --check .

      - name: Lint
        shell: bash -l {0}
        run: flake8 .

      - name: Run tests
        shell: bash -l {0}
        run: pytest -q
